[target.armv7-unknown-linux-gnueabihf]
pre-build = [                                  # additional commands to run prior to building the package
	"apt-get update && apt-get --assume-yes install libopencv-dev clang libclang-dev",
	"apt-get --assume-yes install libdrm-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev mesa-utils",
]  
